"""Stage a single-language documentation tree and its Zensical configuration.

Zensical has no i18n plugin, so translations are handled here instead. A
translation lives next to its English source as `docs/**/<name>.<lang>.md`, and
this script turns that into a complete single-language `docs/` tree:

    build/i18n/<lang>/docs/     copy of docs/, with <name>.<lang>.md moved
                                over <name>.md — pages without a translation
                                simply keep their English content
    build/i18n/<lang>/zensical.toml
                                zensical.toml with the site metadata, the nav
                                titles and the UI labels from i18n/<lang>.toml
                                applied, pointed at the staged tree

The whole tree is copied, not just the translated pages, because the live
editor embeds reference their exercise sources through depth-sensitive raw HTML
attributes (`start="../../code/..."`) that Zensical does not rewrite. The
sources therefore have to exist at the same relative depth under `/<lang>/`.

**English is staged the same way.** Zensical has no way to exclude files from a
build, so building `docs/` directly would publish every `<name>.<lang>.md` as an
extra page (and index it for search) in the English site. Running the default
language through the same staging strips them.

Usage:

    uv run python scripts/build_i18n.py ja
    uv run python scripts/generate_slides.py --docs-dir build/i18n/ja/docs
    uv run zensical build -f build/i18n/ja/zensical.toml

`scripts/build.sh` runs the whole pipeline for every language.

For local development, `--serve` does the staging and starts Zensical's dev
server against the staged tree, re-staging whenever a source file changes:

    uv run python scripts/build_i18n.py ja --serve
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import time
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = ROOT / "docs"
I18N_DIR = ROOT / "i18n"
BUILD_DIR = ROOT / "build" / "i18n"
CONFIG_FILE = ROOT / "zensical.toml"

# The source language. Its build is the one served from the site root; every
# other language is served from /<lang>/.
DEFAULT_LANG = "en"

# `<name>.<lang>.md`, e.g. `getting-started.ja.md`. Language tags are matched
# loosely (ISO 639-1, optionally with a region) so adding a language only means
# adding an `i18n/<lang>.toml`.
TRANSLATION_RE = re.compile(
    r"^(?P<stem>.+)\.(?P<lang>[a-z]{2}(?:-[A-Za-z]{2,4})?)\.md$"
)

# Generated by scripts/generate_slides.py into docs/ — regenerated per language.
SLIDE_SUFFIX = "_slide"


def available_languages() -> list[str]:
    """Language tags that have a translation catalog under `i18n/`."""
    if not I18N_DIR.is_dir():
        return []
    return sorted(path.stem for path in I18N_DIR.glob("*.toml"))


def load_catalog(lang: str) -> dict[str, Any]:
    catalog = I18N_DIR / f"{lang}.toml"
    if not catalog.is_file():
        raise SystemExit(
            f"error: no translation catalog at {catalog.relative_to(ROOT)}"
        )
    with catalog.open("rb") as handle:
        return tomllib.load(handle)


def plan_tree(lang: str) -> dict[Path, Path]:
    """Map each staged path (relative to the docs root) to its source file.

    A `<name>.<lang>.md` is planned at `<name>.md`, so it lands on top of the
    English page; translations for other languages are left out entirely.
    """
    plan: dict[Path, Path] = {}
    translations: dict[Path, Path] = {}

    for source in DOCS_DIR.rglob("*"):
        if not source.is_file():
            continue
        relative = source.relative_to(DOCS_DIR)
        if relative.name.endswith(f"{SLIDE_SUFFIX}.html"):
            continue

        match = TRANSLATION_RE.match(relative.name)
        if not match:
            plan[relative] = source
        elif match["lang"] == lang:
            translations[relative.with_name(f"{match['stem']}.md")] = source

    # Applied last so a translation always wins over its English source.
    plan.update(translations)
    return plan


def stage_docs(lang: str, target: Path) -> tuple[int, int]:
    """Sync `docs/` into `target`, resolving `<name>.<lang>.md` overrides.

    Only files that are missing or out of date are copied, and files with no
    source are removed, so re-running this on every keystroke during `--serve`
    stays cheap and leaves Zensical's own watcher with a minimal diff. Slide
    decks generated into the staged tree are left alone.

    Returns the number of pages translated and the number left in English.
    """
    plan = plan_tree(lang)
    target.mkdir(parents=True, exist_ok=True)

    for existing in target.rglob("*"):
        if not existing.is_file():
            continue
        relative = existing.relative_to(target)
        if relative.name.endswith(f"{SLIDE_SUFFIX}.html"):
            continue
        if relative not in plan:
            existing.unlink()

    for relative, source in plan.items():
        destination = target / relative
        if destination.exists():
            current, wanted = destination.stat(), source.stat()
            if (
                current.st_size == wanted.st_size
                and current.st_mtime_ns >= wanted.st_mtime_ns
            ):
                continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

    pages = {relative for relative in plan if relative.suffix == ".md"}
    translated = sum(1 for relative in pages if plan[relative].name != relative.name)
    return translated, len(pages) - translated


def stage_overrides(target: Path) -> None:
    """Mirror `overrides/` into the staged project root.

    `theme.custom_dir` is resolved against the config file's directory, so the
    theme partials have to be reachable from there.
    """
    source = ROOT / "overrides"
    if not source.is_dir():
        return
    target.mkdir(parents=True, exist_ok=True)
    for path in source.rglob("*"):
        if not path.is_file():
            continue
        destination = target / path.relative_to(source)
        if destination.exists():
            current, wanted = destination.stat(), path.stat()
            if (
                current.st_size == wanted.st_size
                and current.st_mtime_ns >= wanted.st_mtime_ns
            ):
                continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, destination)


def watched_sources() -> dict[Path, tuple[int, int]]:
    """Fingerprint every input the staged tree is derived from."""
    roots = [DOCS_DIR, I18N_DIR, ROOT / "overrides"]
    state: dict[Path, tuple[int, int]] = {}
    for root in roots:
        if not root.is_dir():
            continue
        for path in root.rglob("*"):
            if not path.is_file() or path.name.endswith(f"{SLIDE_SUFFIX}.html"):
                continue
            info = path.stat()
            state[path] = (info.st_size, info.st_mtime_ns)
    info = CONFIG_FILE.stat()
    state[CONFIG_FILE] = (info.st_size, info.st_mtime_ns)
    return state


def serve(lang: str, target: Path, config: Path, dev_addr: str | None) -> int:
    """Run Zensical's dev server against the staged tree, re-staging on edits.

    Zensical watches its own `docs_dir`, which here is the staged copy — so an
    edit to `docs/**/*.ja.md` would otherwise never reach it. This polls the
    real sources and syncs the staged tree, which Zensical then picks up and
    rebuilds as usual.
    """
    command = [sys.executable, "-m", "zensical", "serve", "-f", str(config)]
    if dev_addr:
        command += ["--dev-addr", dev_addr]

    process = subprocess.Popen(command, cwd=ROOT)
    state = watched_sources()
    try:
        while process.poll() is None:
            time.sleep(1)
            current = watched_sources()
            if current == state:
                continue
            state = current
            catalog = load_catalog(lang)
            translated, fallback = stage_docs(lang, target / "docs")
            stage_overrides(target / "overrides")
            stage_config(lang, catalog, target)
            print(
                f"re-staged {lang}: {translated} translated, {fallback} English",
                flush=True,
            )
        return process.returncode or 0
    except KeyboardInterrupt:
        return 0
    finally:
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()


def translate_nav(nav: Any, titles: dict[str, str]) -> Any:
    """Recursively replace English nav titles with their translations.

    Nav entries are either a plain path string (the title then comes from the
    page heading and is already translated by the staged `.md`) or a
    single-key mapping of title to path or child list.
    """
    if isinstance(nav, list):
        return [translate_nav(item, titles) for item in nav]
    if isinstance(nav, dict):
        return {
            titles.get(key, key): translate_nav(value, titles)
            for key, value in nav.items()
        }
    return nav


def stage_config(lang: str, catalog: dict[str, Any], target: Path) -> Path:
    """Write the per-language `zensical.toml` next to the staged docs tree."""
    with CONFIG_FILE.open("rb") as handle:
        config = tomllib.load(handle)

    project = config["project"]
    if "site_name" in catalog:
        project["site_name"] = catalog["site_name"]
    if "site_description" in catalog:
        project["site_description"] = catalog["site_description"]
    if "nav" in project:
        project["nav"] = translate_nav(project["nav"], catalog.get("nav", {}))

    # Zensical treats the config file's directory as the project root and
    # resolves docs_dir, site_dir and theme.custom_dir against it, so the staged
    # directory is a self-contained project: docs/, overrides/ and site/ all sit
    # next to the generated config.
    project["docs_dir"] = "docs"
    project["site_dir"] = "site"

    theme = project.setdefault("theme", {})
    theme["language"] = lang

    # The light/dark toggle labels are authored here rather than coming from
    # Zensical's own catalog, so they need translating too.
    palette_titles = catalog.get("palette", {})
    for palette in theme.get("palette", []):
        toggle = palette.get("toggle")
        if isinstance(toggle, dict) and "name" in toggle:
            toggle["name"] = palette_titles.get(toggle["name"], toggle["name"])

    extra = project.setdefault("extra", {})
    extra["ui"] = catalog.get("ui", {})

    destination = target / "zensical.toml"
    rendered = dumps_toml({"project": project})
    # Only touch the file when it actually changes, so a re-stage during
    # `--serve` does not make Zensical reload a config that is identical.
    if not destination.exists() or destination.read_text(encoding="utf-8") != rendered:
        destination.write_text(rendered, encoding="utf-8")
    return destination


def dumps_toml(data: Any) -> str:
    """Serialise a config back to TOML.

    The standard library only reads TOML, and the config is small and made of
    plain scalars, lists and tables, so a minimal writer avoids adding a
    dependency. Everything is emitted inline under a single `[project]` table
    to keep the generated file trivial to diff against `zensical.toml`.
    """
    lines = ["# Generated by scripts/build_i18n.py — do not edit.", ""]
    for table, values in data.items():
        lines.append(f"[{table}]")
        for key, value in values.items():
            lines.append(f"{key} = {dumps_value(value)}")
        lines.append("")
    return "\n".join(lines)


def dumps_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        escaped = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\t", "\\t")
        )
        return f'"{escaped}"'
    if isinstance(value, list):
        items = ", ".join(dumps_value(item) for item in value)
        return f"[{items}]"
    if isinstance(value, dict):
        items = ", ".join(
            f"{dumps_key(key)} = {dumps_value(item)}" for key, item in value.items()
        )
        return f"{{{items}}}"
    raise TypeError(f"cannot serialise {type(value).__name__} to TOML")


def dumps_key(key: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_-]+", key):
        return key
    return dumps_value(key)


def main() -> int:
    languages = available_languages()
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "lang",
        nargs="?",
        choices=languages or None,
        help=f"language to stage ({', '.join(languages) or 'none available'})",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print the available languages and exit",
    )
    parser.add_argument(
        "--default-lang",
        action="store_true",
        help="print the language served from the site root and exit",
    )
    parser.add_argument(
        "--serve",
        action="store_true",
        help="stage, then run Zensical's dev server, re-staging as you edit",
    )
    parser.add_argument(
        "--dev-addr",
        help="address for --serve, e.g. 127.0.0.1:8000",
    )
    args = parser.parse_args()

    if args.default_lang:
        print(DEFAULT_LANG)
        return 0
    if args.list:
        print(" ".join(languages))
        return 0
    if not args.lang:
        parser.error("a language is required unless --list is given")

    lang = args.lang
    catalog = load_catalog(lang)
    target = BUILD_DIR / lang
    target.mkdir(parents=True, exist_ok=True)

    translated, fallback = stage_docs(lang, target / "docs")
    stage_overrides(target / "overrides")
    config = stage_config(lang, catalog, target)

    print(
        f"staged {lang}: {translated} translated page(s), "
        f"{fallback} falling back to English -> {config.relative_to(ROOT)}"
    )

    if args.serve:
        return serve(lang, target, config, args.dev_addr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
