"""Generate docs/assets/live-editor/keys.js from API keys.

The live-editor widget replaces `__<NAME>__` placeholders in example code
with these keys at run time (see docs/assets/live-editor/live-editor.js).

Sources, in order of precedence:
1. Process environment variables (this is what Cloudflare Pages provides
   at build time — set them in the Pages project settings).
2. A local `.env` file at the repository root (KEY=value lines).

Run before building the site:

    uv run python scripts/generate_keys.py && uv run zensical build

Missing keys are written as empty strings; the widget then shows a friendly
message instead of a provider error.
"""

from pathlib import Path

KEY_NAMES = ["MAPBOX_ACCESS_TOKEN", "GOOGLE_MAPS_API_KEY", "ARCGIS_API_KEY"]

ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = ROOT / "docs" / "assets" / "live-editor" / "keys.js"
ENV_FILE = ROOT / ".env"


def read_dotenv(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip().strip("'\"")
    return values


def main() -> None:
    import os

    dotenv = read_dotenv(ENV_FILE)
    keys = {name: os.environ.get(name) or dotenv.get(name, "") for name in KEY_NAMES}

    lines = ",\n".join(f'  {name}: "{value}"' for name, value in keys.items())
    OUT_FILE.write_text(
        "// Generated by scripts/generate_keys.py — do not edit, do not commit.\n"
        f"export default {{\n{lines}\n}};\n"
    )

    provided = [name for name, value in keys.items() if value]
    missing = [name for name in KEY_NAMES if name not in provided]
    print(f"Wrote {OUT_FILE.relative_to(ROOT)}")
    print(f"  provided: {', '.join(provided) or '(none)'}")
    if missing:
        print(
            f"  missing:  {', '.join(missing)} (examples needing them will show a notice)"
        )


if __name__ == "__main__":
    main()
