name: CI for Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v9

      - name: Install dependencies
        run: |
          uv sync --extra dev

      - name: Build Zensical
        run: |
          uv run zensical build

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: Lint check with ruff
        run: |
          ruff check --fix --config=pyproject.toml

      - name: Format check with ruff
        run: |
          ruff format --config=pyproject.toml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: apply formatting changes
          branch: ${{ github.head_ref }}